# Generated by Django 5.1.4 on 2025-01-03 07:47

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radar',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
