# Generated by Django 5.1.4 on 2025-01-28 15:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("radars", "0002_segment_technology"),
    ]

    operations = [
        migrations.AddField(
            model_name="radar",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FF0000", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
